name: fleet_manager
description: Application de gestion de flotte camion professionnelle
publish_to: 'none'
version: 1.0.5+9

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  firebase_storage: ^13.0.5

  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # UI & Animations
  flutter_animate: ^4.3.0
  shimmer: ^3.0.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1

  # Charts
  fl_chart: ^0.69.0

  # Icons
  cupertino_icons: ^1.0.8

  # Version & Update
  package_info_plus: ^8.1.3
  url_launcher: ^6.3.1

  # Utils
  google_fonts: ^6.1.0
  intl: any
  go_router: ^13.0.1
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  flutter_localizations:
    sdk: flutter

  # Icons
  iconsax: ^0.0.8

  # Forms & Validation
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.0.0
  xml: ^6.6.1
  share_plus: ^12.0.1
  path_provider: ^2.1.5
  web: ^1.1.1

  # Export Excel & PDF
  excel: ^4.0.6
  pdf: ^3.11.1
  printing: ^5.13.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo.png"
  remove_alpha_ios: true
  min_sdk_android: 21
  web:
    generate: false

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/translations/

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Regular.otf
        - asset: assets/fonts/Satoshi-Medium.otf
          weight: 500
        - asset: assets/fonts/Satoshi-Bold.otf
          weight: 700
        - asset: assets/fonts/Satoshi-Black.otf
          weight: 900
